import type { Metadata } from "next";
import type { Viewport } from 'next';
import { Inter } from "next/font/google";
import "./globals.css";

import Nav from "@/components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1
}

export const metadata: Metadata = {
  title: "Transfer Password",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>

          <Nav></Nav>

          <div className="flex justify-center">
            <div className="lg:w-[768px] md:w-[585px] w-full p-2">
              {children}
            </div>
          </div>

        </body>
      </html>
    </>
  );
}
