import type { Metadata } from "next";
import type { Viewport } from 'next';
import { Inter } from "next/font/google";
import "./globals.css";

import Nav from "@/components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1
}

export const metadata: Metadata = {
  title: "Transfer Password",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <div className="w-full items-center flex flex-col space-y-3">
            <Nav></Nav>
            <main className="flex flex-col items-center justify-between">
              <div className="lg:w-[768px] md:w-[585px] sm:w-96 space-y-3 items-center flex flex-col px-3">
                {children}
              </div>
            </main>
          </div>
        </body>
      </html>
    </>
  );
}
